### ISSUE TITLE
"fcose" layout not in the list of possible layouts.

### ISSUE THREAD

**Issue by henriksergoyan** [plotly/dash-cytoscape#119]
#### Description
Cytospace.js has recently announced about a new type of CoSE family, called fcose. I would like to have fcose in the list of dash-cytospace layouts.

**Comment by xhlulu** [comment]
@henriksergoyan Great news, it'd be a great addition to Dash! If you would like to contribute that new feature by starting a PR, we'd be happy to review it :)

See this PR for a reference: https://github.com/plotly/dash-cytoscape/pull/88

**Comment by h2kh** [comment]
The updates above indicate that fcose was added to the library. But I can't access it in my program. Can anyone explain how this works? I'm not too familiar with the development process so apologies in advance if I'm wrong in assuming that the fix above, after merging, should allow me to access fcose
