### ISSUE TITLE
Test useRef branch on react-cytoscape-js

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-cytoscape#130]
This PR should be tested before merging in react-cytoscapejs: https://github.com/plotly/react-cytoscapejs/pull/53

Also add the following:
- https://github.com/plotly/react-cytoscapejs/pull/72
- https://github.com/plotly/react-cytoscapejs/pull/70
- https://github.com/plotly/react-cytoscapejs/pull/67
- https://github.com/plotly/react-cytoscapejs/pull/59
- https://github.com/plotly/react-cytoscapejs/pull/54
- https://github.com/plotly/react-cytoscapejs/pull/50
- https://github.com/plotly/react-cytoscapejs/pull/40

**Comment by kinimesi** [comment]
Tested and merged, closing.
