### ISSUE TITLE
Support for 3rd party layouts

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-cytoscape#32]
Many great external and 3rd party layouts exist for Cytoscape.js, for example:
* Dagre: https://github.com/cytoscape/cytoscape.js-dagre
* Euler: https://github.com/cytoscape/cytoscape.js-euler
* Spread: https://github.com/cytoscape/cytoscape.js-spread
* Klay: https://github.com/cytoscape/cytoscape.js-klay

In order to be used, they need to be added as a dependency to the Dash Cytoscape package, i.e. modify the source code located at `src/lib/Cytoscape.react.js`. If we do this, the distribution will become heavier, but worth it if many people use those.

Is this a feature that the community would be interested in? Please let us know in this thread!

**Comment by Akronix** [comment]
We might find the Klay layout interesting to have.

**Comment by vivekvs1** [comment]
Yes! :) That would definitely be a very useful inclusion according to me. Thanks @xhlulu

**Comment by vetertann** [comment]
Yes! Dagre or sugiyama layouts are very nice for control-flow diagrams

**Comment by xhlulu** [comment]
@vetertann Could you share me the link to sugiyama layout?

**Comment by vetertann** [comment]
@xhlulu Oh, sorry. I only meant that Dagre is based on techniques from the Sugiyama paper. I don't know any other sugiyama implementation for cytoscape..Except for yFiles, but those are not free.
(Support for iGraph might be a "tough" workaround though: it has sugiyama layout, I use it with Dash cytoscape only as layout generator, and the results are great)

**Comment by xhlulu** [comment]
@vetertann @Akronix @vivekvs1 I've opened a working branch for the external layout! I've added a few of the officially supported 3rd party layouts to dash-cytoscape. Here it is: https://github.com/plotly/dash-cytoscape/tree/external-layout-experiments

Please check out the `usage-events.py` and `usage-elements.py` to see the layouts in action! It is not deployed on Pypi so you will have to clone and create your own venv. Please read the CONTRIBUTING and README for more details on the setup.

I can't merge it yet, since I'll need to run some tests, and optimize the package size and the startup time. For now, feel free to try out the WIP version and lmk your thoughts!

**Comment by vivekvs1** [comment]
Wow thanks @xhlulu. That was very fast. I shall give it a try and update.

**Comment by vetertann** [comment]
That was fast:) thank you!

**Comment by xhlulu** [comment]
This issue will be closed once https://github.com/plotly/dash-cytoscape/pull/46 will be merged.

**Comment by vivekvs1** [comment]
@xhlulu  Just tried our the new layouts- just amazing. Really love the 'dagre' layout. Very smart presentation!
