### ISSUE TITLE
[Feature request] animation interface

### ISSUE THREAD

**Issue by vetertann** [plotly/dash-cytoscape#34]
Frames-like animation feature would be nice addition. Currently it is possible to simulate, for example, node movement by changing its position incrementally, but that is possible only by changing all elements for dcc. Animation made this way not as smooth as layout change animation, and leads to constant app update.

**Comment by xhlulu** [comment]
Would those change in position be linear? If so, you could make a single callback to updates the layout from "preset" with a list of positions to "preset", but with a different list of positions.

They reason why it is not as smooth is because every callback being fired is a request, so there's a minimum amount of time required for the data to move from the server to the browser.

**Comment by vetertann** [comment]
Well, that is what I was trying so far, changing elements, than changing preset to preset; maybe I dont give layout enough time for animation, as I'm triyng to achieve smoothness using frequency of dcc.Intervals.
Non-linear movement could be achieved by approximation, but I can see possible difficultions in transition speed control in this approach. 
Two transitions metrics to control: interval from dcc.Intervals and animation duration from layout, plus minimal movement distance for non-linear approximation. A lot of plates to spin:)

**Comment by vetertann** [comment]
Or it just that I cant update positions and layout simultaneously

**Comment by vetertann** [comment]
@xhlulu, could you please give me a hint how to put both elements and layout into single callback? Multiple outputs are but allowed, and dcc doesn't seem to have  something like compound "figure" parameter

**Comment by xhlulu** [comment]
Check out the new Dash release, I believe it is now possible to have multiple outputs.

**Comment by xhlulu** [comment]
You can also specify the position of the elements directly in the layout property. Please check out the Cytoscape.js docs, specifically the preset layout section.

**Comment by vetertann** [comment]
Wow, thank you so much! I'll try it all:)
