### ISSUE TITLE
Wheel sensitivity control for zoom

### ISSUE THREAD

**Issue by vivekvs1** [plotly/dash-cytoscape#41]
Hi,

What would be the way to set the mouse wheel sonesitivy for zooming? I see that cytoscape.js has `wheelSensitivity ` parameter to adjust the sensitivity. I couldn't get that to work in Dash-Cytoscape

Thanks,
Vivek

**Comment by xhlulu** [comment]
If this prop is not available in react-cytoscapejs, then it will not be available for Dash-cytoscape either... I would suggest you to open up an issue on https://github.com/plotly/react-cytoscapejs/!

**Comment by vivekvs1** [comment]
Thanks, I see that you have already raised an issue for including rendering parameters.

**Comment by xhlulu** [comment]
Sounds good! I'll close this PR until there's an update on the react side. Feel free to reopen if needed!

**Comment by felipeboffnunes** [comment]
Any updates?
