### ISSUE TITLE
Viewport Responsiveness

### ISSUE THREAD

**Issue by invokermain** [plotly/dash-cytoscape#62]
Hi,

I want to use cytoscape for a company dashboard, but one of our requirements it is viewable on mobile. So far I have had no issues making dash look good on mobile using some css hacks/media queries etc.

But I am struggling to make cytoscape responsive. It seems that the layout is fit to the viewport on initial render but any change to the viewport size does not fire the appropriate fit callback.

Is this intended or configurable?

On resize (not fit to viewport):

![image](https://user-images.githubusercontent.com/44192816/59755532-faef4f00-927f-11e9-91a4-c5ab80fb446b.png)

On refresh (fits now):

![image](https://user-images.githubusercontent.com/44192816/59755605-240fdf80-9280-11e9-8f39-e733a5df2575.png)

**Comment by CloudZazu** [comment]
I have the same concern. Though it might require adding more functionality to the cytoscape javascript library for that. Attempted to resize some of the galleries on http://js.cytoscape.org/.

**Comment by mj3cheun** [comment]
There is a solution in the works attempting to fix this problem. A branch containing a beta version of this solution should be released shortly for testing.

**Comment by mj3cheun** [comment]
https://github.com/plotly/dash-cytoscape/tree/responsive-graph-beta

A new branch has been made containing the responsive graph feature. Note that by default this feature is turned off so that default behavior remains the same. To turn it on, use `responsive=true`. More testing is needed before this feature can be finalized. Please let me know if there are any bugs.

**Comment by invokermain** [comment]
hey mj3cheun, sorry for the delay, I just tested this and it works, thank you!

**Comment by xhlulu** [comment]
Closing this since https://github.com/plotly/dash-cytoscape/pull/92 was merged.
