### ISSUE TITLE
CI: Test against Python 2.7

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-cytoscape#78]

**Comment by xhlulu** [comment]
Are we still interested in this?

**Comment by alexcjohnson** [comment]
Unfortunately yes, py27 is still something we need to support so should be tested.

**Comment by kinimesi** [comment]
Support for Python 2.7 is going to be dropped. Please see: https://community.plotly.com/t/sunsetting-python-2-support/54893
