### ISSUE TITLE
cytoscape graphs are drawn off screen on first render

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-cytoscape#86]
Might be related to the latest async changes

![image](https://user-images.githubusercontent.com/1280389/81433033-c7781600-9118-11ea-9920-e8bc87fcef79.png)

**Comment by xhlulu** [comment]
@chriddyp It seems like the docs are rendering well in the DE docs. Could there be some significant difference in how both are rendered?

**Comment by chriddyp** [comment]
@xhlulu - I see this on the open source docs, not just the DE ones:
![image](https://user-images.githubusercontent.com/1280389/84943014-96382180-b098-11ea-9873-48ab30c70e3e.png)

**Comment by xhlulu** [comment]
Yeah, on the DE docs they look fine to me:
![image](https://user-images.githubusercontent.com/21180505/84959945-758abe80-b0ce-11ea-916e-895224636e63.png)

**Comment by xhlulu** [comment]
Perhaps we an look into the difference between the `dash-docs` and the DED repos to find the culprit?

**Comment by xhlulu** [comment]
Fixed in v0.2.0
