### ISSUE TITLE
Clarify usage of yarn vs npm in contributing.md

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-cytoscape#93]
Right now, it's not clear in `contributing.md` whether yarn or npm should be used. Since `yarn` was chosen to be the package manager, we should more clearly indicate that in contributing.

**Comment by IvoLeist** [comment]
Hey @xhlulu

sorry for being so silent in the last weeks but I am right now in a job transition phase
and therefore very busy with preparing a proper handover + doing all the necessary paperwork
for moving to Barcelona.

Anyway long story short:
I just want to give you a heads up that at least in my old project building with Yarn
lead to a buggy behaviour of the compound nodes.
Meaning if I dragged a compound node I would not move any longer the whole comound node
but each element individually

When using npm everything worked as expected.

Best,
Ivo
