### ISSUE TITLE
Dash Cytoscape: control the scroll wheel sensitivity for zooming

### ISSUE THREAD

**Issue by ZhabizGIT** [plotly/dash-cytoscape#97]
Hello,

I need to control the scroll wheel sensitivity to zoom on canvas and change the scale of graphs. I noticed that cytoscape.js and react-cytoscapejs have supported the wheel-sensitivity property in their last updates to control the scroll to zoom in/out on graphs. I was wondering if there is a way to limit the fast scroll behavior in dash-cytoscape?

Thanks,

**Comment by xhlulu** [comment]
Hi, it seems like this is a new feature added to Cytoscape.js. Could you let me know which prop you would like to control specifically?

**Comment by ZhabizGIT** [comment]
I didn't check the release-notes to see when it was added. The name of property is wheelSensitivity. It is described here: https://js.cytoscape.org/#init-opts/wheelSensitivity

I noticed react-cytoscapejs is also supported that from [v1.2.0](https://github.com/plotly/react-cytoscapejs). So it would be great to have that here as well.

**Comment by felipeboffnunes** [comment]
I'm looking forward to have a custom wheelSensitivity too! Is there any delivery forecast for it?

**Comment by ant1j** [comment]
That would be super useful. Thanks

**Comment by Rodolphe2005** [comment]
I'm also interested.

**Comment by CaseGuide** [comment]
Anyone figure out how to control wheelSensitivity in Plotly Dash?
